#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect above requirements

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
SERVER_CONFIG=\
"server {
    listen 80;
    server_name https://www.github.com/MokoneSA;
    return 301 http://simonlephoto.tech;
}"
bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"

sudo service nginx restart
